### ISSUE TITLE
登录验证问题

### ISSUE THREAD

**Issue by viewhang** [lqsong/admin-antd-vue#4]
1.缺少`@menu-dark-submenu-bg`，我在`antd-variables.less`文件中加了，能跑起来了
2.登录时候报错了，然后提示验证不通过
![image](https://user-images.githubusercontent.com/26957298/124690988-a45c1880-df0d-11eb-86c6-be1f84c2e4a9.png)

所以我还是没进得了首页。。

环境` Windows 10` `chrome 91` `node12` 两个分支一样的问题

**Comment by lqsong** [comment]
`ant-design-vue` 版本问题，如果你这边急用可以吧 `ant-design-vue` 设置 `2.1`版本，先不用`2.2`，这边后续会升级。

**Comment by lqsong** [comment]
`ant-design-vue` 版本问题，如果你这边急用可以吧 `ant-design-vue` 设置 `2.1`版本，先不用`2.2`，这边后续会升级。

**Comment by viewhang** [comment]
我使用的是`2.1.6`版本依然不行

**Comment by lqsong** [comment]
代码已更新，请拉取最新代码

**Comment by viewhang** [comment]
更新最新代码->删除项目下`node_modules` ->`yarn` ->`yarn dev`.还是不行

**Comment by lqsong** [comment]
不好意思，刚看清楚，只是解决了问题1，还有一个问题2，稍等，正在修复

**Comment by lqsong** [comment]
> 更新最新代码->删除项目下`node_modules` ->`yarn` ->`yarn dev`.还是不行

已修复
