### ISSUE TITLE
有vue3的真实数据例子吗 真实的查询和分页

### ISSUE THREAD

**Issue by stevenliu87** [lqsong/admin-antd-vue#6]

**Comment by lqsong** [comment]
后台前端就是真实的啊，只是返回的数据是mockdata

**Comment by stevenliu87** [comment]
后台接口中没传 查询条件呀，分页也没传到后台 ，有传查询条件和分页的例子吗

**Comment by lqsong** [comment]
![image](https://user-images.githubusercontent.com/22975974/125430961-3675e0aa-2216-43be-bef7-3515cd35b1bf.png)

**Comment by stevenliu87** [comment]
你的api中没有接收呀

**Comment by stevenliu87** [comment]
有传查询条件和分页的例子吗

**Comment by lqsong** [comment]
你可以参考:[https://github.com/lqsong/lqsblog-frontend-admin-vue](https://github.com/lqsong/lqsblog-frontend-admin-vue)

**Comment by stevenliu87** [comment]
这个是vue3.0的吗

**Comment by lqsong** [comment]
vue2 , 逻辑一样

**Comment by stevenliu87** [comment]
有3.0的吗

**Comment by stevenliu87** [comment]
差的太远了 3.0用的是ts

**Comment by lqsong** [comment]
没有

**Comment by lqsong** [comment]
后期有时间上个样例吧

**Comment by stevenliu87** [comment]
想用你的3.0写项目 可没有真实的查询和分页呀

**Comment by stevenliu87** [comment]
期待尽快吧
