### ISSUE TITLE
运行没有问题，但是打包后运行报错

### ISSUE THREAD

**Issue by luoqiz** [lqsong/admin-antd-vue#9]
![image](https://user-images.githubusercontent.com/22161059/175772913-4dbea122-5192-413b-b4ff-03c3b07825b3.png)
![image](https://user-images.githubusercontent.com/22161059/175772932-b0410d74-13a8-4932-8093-8f8b8f3bb2f9.png)

**Comment by lqsong** [comment]
测试，没有问题，请提供你的在线代码

**Comment by luoqiz** [comment]
我邀请您进入项目了，您查收一下。

**Comment by lqsong** [comment]
用户密码

**Comment by luoqiz** [comment]
您加入项目后，相当于您的账号已经拥有了项目的管理权，直接使用您自己的账号密码就可以了哈。

**Comment by luoqiz** [comment]
您是说网站的账号密码吧? 我把账号和密码，微信号发到您QQ邮箱 ，方便的话您加我一下吧。

**Comment by lqsong** [comment]
![image](https://user-images.githubusercontent.com/22975974/175889458-ea2f5449-9f28-454f-9108-a117c6e74e7a.png)
看了下是你自己定义的文件出现问题，和本框架原始代码，无关系啊，这个需要你们内部解决。
